image: Visual Studio 2019
platform: x64

clone_depth: 1

environment:
  global:
    VERBOSE: yes
    ARTIFACTS: yes
    OCAML_PLATFORM_NAME: OCamlPlatform
    OCAML_VERSION: 4.10.0
    OPAM_VERSION: 3def1a6d1ff102aaa608f5e9170783b96f55069d
  matrix:
    - PORT: mingw64
      WINDOWS: yes
    - PORT: msvc64
      WINDOWS: yes
    - PORT: cygwin
      WINDOWS: yes
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s linux
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s macos
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - WINDOWS: yes
    environment:
      CYG_ROOT: C:\cygwin64
      CYG_CACHE: '%APPDATA%\cygwin'
      CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    install:
      - call "%APPVEYOR_BUILD_FOLDER%\windows\install.cmd"
    build_script:
      - call "%CYG_ROOT%\bin\bash.exe" "-lc" "$APPVEYOR_BUILD_FOLDER/windows/build.sh"
    cache:
      - '%CYG_CACHE%'


# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
