platform: x64

clone_depth: 1

environment:
  global:
    VERBOSE: yes
    ARTIFACTS: yes
    OCAML_VERSION: 4.10.0
    FLEXDLL_VERSION: bd636def70d941674275b2f4b6c13a34ba23f9c9
    OPAM_VERSION: 846c64c1b6a7daed87cfd939da359e9a6ab73368
    DUNE_VERSION: 2.5.1
    DUNIVERSE_VERSION: 414f2a25354bc2fcd95f9b22018fe633f9969a69

  matrix:

    - job_name: msvc64
      OCAML_PORT: msvc64
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: mingw64
      OCAML_PORT: mingw64
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: Ubuntu
      appveyor_build_worker_image: Ubuntu

    - job_name: macOS
      appveyor_build_worker_image: macOS

    - job_name: cygwin
      OCAML_PORT: auto
      appveyor_build_worker_image: Visual Studio 2019

for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s linux
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s macos
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - appveyor_build_worker_image: Visual Studio 2019
    environment:
      BUILD_FOLDER: '%APPVEYOR_BUILD_FOLDER%'
    install:
      - call "%APPVEYOR_BUILD_FOLDER%\windows\install.cmd" install
    build_script:
      - call "%APPVEYOR_BUILD_FOLDER%\windows\install.cmd" build
    cache:
      - '%CYG_CACHE%'
      - '%APPVEYOR_BUILD_FOLDER%\ocaml-%OCAML_VERSION%.tar.gz'
      - '%APPVEYOR_BUILD_FOLDER%\flexdll-%FLEXDLL_VERSION%.tar.gz'
      - '%APPVEYOR_BUILD_FOLDER%\opam-%OPAM_VERSION%.tar.gz'
      - '%APPVEYOR_BUILD_FOLDER%\dune-%DUNE_VERSION%.tar.gz'
      - '%APPVEYOR_BUILD_FOLDER%\duniverse-%DUNIVERSE_VERSION%.tar.gz'


# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
