image: Visual Studio 2019
platform: x64

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

    - BUILD: x86_64-pc-cygwin
      HOST: x86_64-pc-windows
    - BUILD: x86_64-pc-msys
      HOST: x86_64-pc-windows

    - BUILD: x86_64-pc-cygwin
      HOST: x86_64-w64-mingw32
    - BUILD: x86_64-w64-mingw32
      HOST: x86_64-w64-mingw32

    # - BUILD: x86_64-pc-cygwin
    #   HOST: x86_64-pc-cygwin
    - BUILD: x86_64-pc-msys
      HOST: x86_64-pc-msys


for:
  -
    matrix:
      only:
        - BUILD: x86_64-pc-cygwin

    environment:
      CYG_ROOT: C:\cygwin64
      CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
      CYG_CACHE: C:/cygwin/var/cache/setup
    install:
      - cmd: call "%APPVEYOR_BUILD_FOLDER%\windows\cygwin.cmd"
    build_script:
      - cmd: bash -lc "$APPVEYOR_BUILD_FOLDER/build.sh -v -s cygwin -B $BUILD -H $HOST"
  -
    matrix:
      only:
        - BUILD: x86_64-pc-msys
        - BUILD: x86_64-w64-mingw32
    install:
      - cmd: call "%APPVEYOR_BUILD_FOLDER%\windows\msys2.cmd"
    build_script:
      - cmd: C:\msys64\usr\bin\bash.exe -lc "$APPVEYOR_BUILD_FOLDER/build.sh -v -s msys2 -B $BUILD -H $HOST"
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -v -s linux
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -v -s macos


# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')
