image: Visual Studio 2019
platform: x64

clone_depth: 1

environment:
  global:
    VERBOSE: yes
    ARTIFACTS: yes
    OCAML_PLATFORM_NAME: OCamlPlatform
    OCAML_VERSION: 4.10.0
    OPAM_VERSION: def89fc4fc1af53bf1f8d420129abc398751cd6c
  matrix:
    - PORT: mingw64
      DEP_MODE: lib-pkg
      WINDOWS: yes
    - PORT: msvc64
      DEP_MODE: lib-ext
      WINDOWS: yes
    - PORT:
      DEP_MODE: lib-ext
      WINDOWS: yes
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

for:
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s linux
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    build_script:
      - $APPVEYOR_BUILD_FOLDER/build.sh -s macos
    cache:
      - $APPVEYOR_BUILD_FOLDER/opam-$OPAM_VERSION/bootstrap
  -
    matrix:
      only:
        - WINDOWS: yes
    environment:
      CYG_ARCH: x86_64
      CYG_ROOT: C:\cygwin64
      CYG_SETUP: '%CYG_ROOT%\setup-%CYG_ARCH%.exe'
      CYG_CACHE: '%APPDATA%\cygwin'
      CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
      BUILD_FOLDER: '%APPVEYOR_BUILD_FOLDER%'
    install:
      - call "%APPVEYOR_BUILD_FOLDER%\windows\install.cmd" install
    build_script:
      - call "%APPVEYOR_BUILD_FOLDER%\windows\install.cmd" pre_build
    cache:
      - '%CYG_CACHE%'
      - '%APPVEYOR_BUILD_FOLDER%\opam\bootstrap'
      - '%APPVEYOR_BUILD_FOLDER%\opam\src_ext\archives'


# Uncomment this to enable Remote Desktop on the build worker at the end of the
# build. The worker is available for the remainder of the allocated hour.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
