language: c

git:
  depth: 1

env:
  global:
    - OCAML_VERSION: 4.10.0
    - OPAM_VERSION: def89fc4fc1af53bf1f8d420129abc398751cd6c

jobs:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      script:
        - docker build --build-arg=OCAML_VERSION=$OCAML_VERSION --build-arg=OPAM_VERSION=$OPAM_VERSION -f "linux/Dockerfile" "linux/"
    - os: linux
      dist: bionic
      script:
        - $TRAVIS_BUILD_DIR/build.sh -s linux
    - os: osx
      script:
        - $TRAVIS_BUILD_DIR/build.sh -s macos

cache:
  directories:
    - opam-$OPAM_VERSION/bootstrap
