name: OCaml Platform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCAML_PLATFORM_NAME: OCamlPlatform
  ARTIFACTS: yes

  OCAML_VERSION: 4.11.1
  FLEXDLL_VERSION: 0.38
  OPAM_VERSION: cbb5ba6b76e6019e13f9a0f4c40ae8822f07ffd3
  DUNE_VERSION: 2.7.1
  OPAM_MONOREPO_VERSION: b06a55edaa33d5773f22563f45cfe1868f63bc67
  MSVS_TOOLS_VERSION: 0.4.1

jobs:
  op_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s linux
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ env.OCAML_PLATFORM_NAME }}.tar.gz

  op_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s macos
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ env.OCAML_PLATFORM_NAME }}.tar.gz

  op_windows:
    strategy:
      fail-fast: false
      matrix:
        ocaml-port: [msvc64, mingw64]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
      OCAML_PORT: ${{ matrix.ocaml-port }}
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: call "%GITHUB_WORKSPACE%\windows\install.cmd" all
      env:
        PROJECT_FOLDER: ${{ github.workspace }}
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ env.OCAML_PLATFORM_NAME }}_Installer.exe"
