name: OCaml Platform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCAML_VERSION: 4.10.0
  FLEXDLL_VERSION: bd636def70d941674275b2f4b6c13a34ba23f9c9
  OPAM_VERSION: 9f2f9004f806f7b235a38e92256a6538fcaba2b2
  DUNE_VERSION: 2.6.0
  DUNIVERSE_VERSION: 414f2a25354bc2fcd95f9b22018fe633f9969a69

jobs:
  op_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s linux
  op_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s macos
  op_windows:
    strategy:
      matrix:
        ocaml-port: [msvc64, mingw64, auto]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
      OCAML_PORT: ${{ matrix.ocaml-port }}
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: call "%GITHUB_WORKSPACE%\windows\install.cmd" install
    - name: build
      run: call "%GITHUB_WORKSPACE%\windows\install.cmd" build
