name: OCaml Platform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCAML_PLATFORM_NAME: OCamlPlatform
  ARTIFACTS: yes

  OCAML_VERSION: 4.10.0
  FLEXDLL_VERSION: ced71439c4292c8ea1cc12cf96c1f94510b5c25b

  OPAM_VERSION: f005e46d52ab9c524dc6955f06090bd939fb40e8
  OPAM_URL: https://github.com/MisterDA/opam/${{ env.OPAM_VERSION }}.tar.gz

  DUNE_VERSION: 2.6.0
  DUNIVERSE_VERSION: 47faea8522e8e44ba0dbd04403425970aa5c2662
  MSVS_TOOLS_VERSION: 0.4.1

jobs:
  op_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s linux
    - uses: actions/upload-artifact@v2
      with:
        path: $OCAML_PLATFORM_NAME.tar.gz

  op_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: $GITHUB_WORKSPACE/build.sh -s macos
    - uses: actions/upload-artifact@v2
      with:
        path: $OCAML_PLATFORM_NAME.tar.gz

  op_windows:
    strategy:
      fail-fast: false
      matrix:
        ocaml-port: [msvc64, mingw64, auto]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    env:
      OCAML_PORT: ${{ matrix.ocaml-port }}
    steps:
    - uses: actions/checkout@v2
    - name: OCaml Platform build
      run: call "%GITHUB_WORKSPACE%\windows\install.cmd" all
    - uses: actions/upload-artifact@v2
      with:
        path: "${OCAML_PLATFORM_NAME}_Installer.exe"
