name: OCaml Platform Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCAML_VERSION: 4.10.0
  FLEXDLL_VERSION: bd636def70d941674275b2f4b6c13a34ba23f9c9
  OPAM_VERSION: 9f2f9004f806f7b235a38e92256a6538fcaba2b2
  DUNE_VERSION: 2.6.0
  DUNIVERSE_VERSION: 414f2a25354bc2fcd95f9b22018fe633f9969a69

defaults:
  runs-on: windows-latest
  run:
    shell: cmd
  steps:
  - uses: actions/checkout@v2
  - name: install
    run: call "%GITHUB_WORKSPACE%\windows\install.cmd" install
  - name: build
    run: call "%GITHUB_WORKSPACE%\windows\install.cmd" build

jobs:
  op_msvc64:
    env:
      OCAML_PORT: msvc64
  op_mingw64:
    env:
      OCAML_PORT: mingw64
  op_cygwin:
    env:
      OCAML_PORT: auto
